### ISSUE TITLE
Too many slaves ports are listed

### ISSUE THREAD

**Issue by thierry-FreeBSD** [blabber/lps#1]
Great idea!

But there is a small issue: on my machine, it displays:

$ ./lps.sh
audio/timidity++ 2.14.0 2.14.0-140821-1200
audio/timidity++-emacs 2.14.0 2.14.0-140821-1200
audio/timidity++-gtk 2.14.0 2.14.0-140821-1200
audio/timidity++-motif 2.14.0 2.14.0-140821-1200
audio/timidity++-slang 2.14.0 2.14.0-140821-1200
audio/timidity++-tcltk 2.14.0 2.14.0-140821-1200
audio/timidity++-xaw 2.14.0 2.14.0-140821-1200
audio/timidity++-xskin 2.14.0 2.14.0-140821-1200

But only timidity-0.2i_1 is installed:

$ pkg info -I timidity
timidity-0.2i_1                MIDI to PCM software synthesizer

**Comment by blabber** [comment]
Thanks for poninting this out. To be honest timidity++ is not even a slave port of timidity.
